### ISSUE TITLE
problem when generating Url with optional parameters

### ISSUE THREAD

**Issue by hdimo** [zendframework/zend-expressive-fastroute#12]
I am using fastrouter as router with this route config

``` php
[
            'name' => 'blog.post.detail',
            'path' => '/blog/post/details/{postId}[/{title}]',
            'middleware' => \Blog\Action\PostSingleAction::class,
            'allowed_methods' => ['GET'],
 ],
```

when generating URL from views with 
`$this->url('blog.post.detail', ['postId'=>1, "title"=>"sometitle"])`
it returns
_web.com/blog/post/details/1[/sometitle]_

**Comment by pine3ree** [comment]
@jkhaled 
I believe this fix always presumes we want to always use the pattern `[/{param}]`.

I often use patterns like `/blog/post/index[-{page}]` to generate urls like
`/blog/post/index`
`/blog/post/index-2`
`/blog/post/index-3`

anyway i tried your route definition and it works for me without the fix. #4 should already fix the bug you are referring to. Are you using the latest version?

kind regards

**Comment by hdimo** [comment]
@pine3ree I just updated to last version and it fixes the path,
thanks

**Comment by pine3ree** [comment]
@jkhaled 
you are welcome!

**Comment by pine3ree** [comment]
@jkhaled 
oh i forgot ...maybe you should close the related PR #13.
:-)
