### ISSUE TITLE
Incorrectly matched methods when using implicit options

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-fastroute#35]
In an expressive app I'm trying to take advantage of the `ImplicitOptionsMiddleware`, however, I've seen the FastRoute router is not properly matching the allowed methods when the same path is used in different routes.

For example, let's consider this routes config:

```php
return [
    [
        'name' => 'get-foo-bar',
        'path' => '/foo/bar',
        'middleware' => App\Action\GetAction::class,
        'allowed_methods' => ['GET'],
    ],
    [
        'name' => 'create-foo-bar',
        'path' => '/foo/bar',
        'middleware' => App\Action\CreateAction::class,
        'allowed_methods' => ['POST', 'PUT'],
    ],
];
```

When using the `ImplicitOptionsMiddleware` and performing an OPTIONS request to the `/foo/bar` path, one would expect the **Allow** header to be `GET,POST,PUT`, however, the router is matching the frst route, and therefore returning `GET` only.

I think the problem is in the router's `match` method, in this block in particular:

```php
if ($result[0] !== Dispatcher::FOUND
    && in_array($method, self::HTTP_METHODS_IMPLICIT, true)
) {
    $introspectionResult = $this->probeIntrospectionMethod($method, $path, $dispatcher);
    if ($introspectionResult) {
        return $this->marshalMatchedRoute($introspectionResult, $method);
    }
}
```

The dispatcher has returned a "not allowed" result, but the second check (in_array for HTTP_METHODS_IMPLICIT), returns true, which calls `marshalMatchedRoute`, making a RouteResult::fromRoute to be returned with the first configured route for the path.

Is that correct? I was going to provide a patch, but I'm not sure if that's an intended behavior.

**Comment by weierophinney** [comment]
Fixed with #52; I'll be releasing a new version shortly that contains it.
